packages:
  - "packages/*"

catalog:
  "@types/node": ^22.8.7
  "@types/react": npm:types-react@rc
  "@types/react-dom": npm:types-react-dom@rc
  react: npm:react@rc
  react-dom: npm:react-dom@rc
  svelte: ^5.1.3
  typescript: ~5.6.2
  vite: ^5.4.9
  vite-tsconfig-paths: ^5.0.1
  vue: ^3.5.12
