packages:
  - "packages/*"

catalog:
  "@types/react": ^18.3.11
  "@types/react-dom": ^18.3.1
  react: ^18.3.1
  react-dom: ^18.3.1
  svelte: ^5.1.3
  typescript: ~5.6.2
  vite: ^5.4.9
  vue: ^3.5.12
