packages:
  - "packages/*"

catalog:
  "@rollup/pluginutils": ^5.1.3
  "@types/node": ^22.8.7
  "@types/react": ^19.0.0
  "@types/react-dom": ^19.0.0
  cross-env: ^7.0.3
  destr: ^2.0.3
  empathic: ^1.0.0
  h3: ^1.13.0
  magic-string: ^0.30.13
  react: ^19.0.0
  react-dom: ^19.0.0
  svelte: ^5.1.3
  typescript: ~5.6.2
  vite: ^5.4.9
  vite-plugin-dts: ^4.3.0
  vite-plugin-externalize-deps: ^0.8.0
  vite-tsconfig-paths: ^5.0.1
  vue: ^3.5.12
